version: "3.7"

services:
  app:
    build: .
    restart: on-failure
    volumes:
      - ./docs:/usr/src/app/docs
      - ./pages:/usr/src/app/pages
      - ./client:/usr/src/app/client
      - ./server:/usr/src/app/server
      - ./scripts:/usr/src/app/scripts
    command: "/bin/sh -c 'yarn dev'"
    ports:
      - 8080:8080
    environment:
      DB_TYPE: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_DATABASE: bouncecode
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bouncecode
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306" # temporary
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  mysqldata:
